import os


def _machine_fast_profile() -> dict:
	cpu_count = os.cpu_count() or 4
	if cpu_count >= 12:
		return {
			"MAX_VISITED": 120000,
			"MAX_FRONTIER": 160000,
			"KEEP_FRONTIER": 70000,
			"KEEP_VISITED": 60000,
			"COMPACTION_GAP": 30000,
			"MAX_MOVES_PER_STATE": 14,
		}
	if cpu_count >= 8:
		return {
			"MAX_VISITED": 100000,
			"MAX_FRONTIER": 130000,
			"KEEP_FRONTIER": 55000,
			"KEEP_VISITED": 48000,
			"COMPACTION_GAP": 25000,
			"MAX_MOVES_PER_STATE": 12,
		}
	return {
		"MAX_VISITED": 80000,
		"MAX_FRONTIER": 100000,
		"KEEP_FRONTIER": 42000,
		"KEEP_VISITED": 36000,
		"COMPACTION_GAP": 20000,
		"MAX_MOVES_PER_STATE": 10,
	}


UCS_PROFILE = _machine_fast_profile()
UCS_MAX_VISITED_STATES = UCS_PROFILE["MAX_VISITED"]
UCS_MAX_FRONTIER_SIZE = UCS_PROFILE["MAX_FRONTIER"]
UCS_FRONTIER_KEEP_SIZE = UCS_PROFILE["KEEP_FRONTIER"]
UCS_VISITED_KEEP_SIZE = UCS_PROFILE["KEEP_VISITED"]
UCS_COMPACTION_GAP = UCS_PROFILE["COMPACTION_GAP"]
UCS_MAX_MOVES_PER_STATE = UCS_PROFILE["MAX_MOVES_PER_STATE"]
